version: "3.8"

services:
  app:
    build:
      context: .
    container_name: mini-wallet-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - api
    environment:
      - NODE_ENV=development
    command: npm run dev

  api:
    image: node:18
    container_name: mini-wallet-api
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    command: sh -c "npm install -g json-server && json-server --watch db.json --port 4000"
